CREATE TABLE `agricity` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`UTCTime` TIMESTAMP NOT NULL,
	`IdEstacao` VARCHAR(20) NOT NULL COLLATE 'utf8_bin',
	`OutdoorTemperature` FLOAT NULL DEFAULT NULL,
	`OutdoorHumidity` FLOAT NULL DEFAULT NULL,
	`Rain60Minutes` FLOAT UNSIGNED NULL DEFAULT NULL,
	`Rain24Hours` FLOAT UNSIGNED NULL DEFAULT NULL,
	`SunlightVisible` INT(10) NULL DEFAULT NULL,
	`SunlightUVIndex` FLOAT NULL DEFAULT NULL,
	`WindSpeed` FLOAT NULL DEFAULT NULL,
	`WindDirection` VARCHAR(5) NULL DEFAULT NULL COLLATE 'utf8_bin',
	`BarometricPressure` FLOAT UNSIGNED NULL DEFAULT NULL,
	`batteryPower` INT(3) UNSIGNED NULL DEFAULT NULL,
	`solarPower` INT(10) UNSIGNED NULL DEFAULT NULL,
	`soilTemperature` INT(5) NULL DEFAULT NULL,
	`soilHumidity` INT(5) UNSIGNED NULL DEFAULT NULL,
	`metal` INT(10) UNSIGNED NULL DEFAULT NULL,
	`lat` FLOAT NULL DEFAULT NULL,
	`lon` FLOAT NULL DEFAULT NULL,
	`Altitude` INT(10) NULL DEFAULT NULL,
	`Vegetacao` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8_bin',
	PRIMARY KEY (`id`) USING BTREE
)
COLLATE='utf8_bin'
ENGINE=InnoDB
;